{
 "title": "Карта георассеянность Http",
 "description": "делал по этой статье  https://volkovlabs.io/blog/nginx-loki-grafana-20230129/#import",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Из каких стран приходят http запросы Nginx",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(geoip_country_code) (count_over_time({filename=\"/var/log/nginx/access.log\", job=\"nginx\"} != `blackbox-exporter` | json | __error__=`` [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Запросы Nginx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({filename=\"/var/log/nginx/access.log\"} != `blackbox-exporter` [$__interval]))"
    }
   ]
  },
  {
   "title": "Время отклика Nginx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_duration_seconds{job=\"wordpress_admin_panel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Логи Nginx ",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/nginx/access.log\"} != `blackbox-exporter` | json | line_format \"{{.request_uri}} with Http status: {{.status}}\"",
     "legendFormat": "syslog"
    }
   ]
  }
 ]
}