groups:

#Правило для Nginx запущен он или упал        
- name: nginx
  rules:
  - alert: NginxDown
    expr: nginx_up == 0
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: "Nginx is down (instance {{ $labels.instance }})"
      description: "Nginx has been down for more than 5 seconds. Current status is {{ $value }}."

#Правило для MySql запущен он или упал
- name: mysql
  rules:
  - alert: MysqlDown
    expr: mysql_up == 0
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: "MySql is down (instance {{ $labels.instance }})"
      description: "MySql has been down for more than 5 seconds. Current status is {{ $value }}."

#Правило для Wordpress запущен он или упал 
- name: wordpressdown
  rules:
  - alert: WordpressHTTPError
    expr: probe_http_status_code{instance="http://194-67-67-115.cloudvps.regruhosting.ru/", job="blackbox"} != 200
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: "HTTP error detected"
      description: "HTTP detected for target {{ $labels.instance }}"


