global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['194.67.67.115:9100']

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['194.67.67.115:9104']

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['194.67.67.115:9113']

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['194.67.67.115:9115']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://194-67-67-115.cloudvps.regruhosting.ru/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 194.67.67.115:9115

  - job_name: 'wordpress_admin_panel'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://194-67-67-115.cloudvps.regruhosting.ru/wp-login.php
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 194.67.67.115:9115


alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 194.67.67.115:9093

