global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['194.67.67.115:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093




