global:
  scrape_interval: 15s

  #rule_files:
  #  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['194.67.67.115:9100']

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['194.67.67.115:9104']

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['194.67.67.115:9113']

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['194.67.67.115:9115']


        #alerting:
        #  alertmanagers:
        #    - static_configs:
        #        - targets:
        #            - alertmanager:9093
        #



