global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  repeat_interval: 10s
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - chat_id: -1001941487247
        parse_mode: 'Markdown'
        bot_token: ''
        #bot_token: ${SUPER_TOKEN}
        send_resolved: true

